project:
  type: book
  output-dir: _site
  execute-dir: project
  
book:
  title: "Review Oriented Development (ROD)"
  author:
    - Yilong Zhang
  description: "A Review Oriented Development Framework using YAML and AI for Clinical Analysis and Reporting"
  output-file: "rod"

  site-url: https://elong0527.github.io/demo-tlf-yaml
  repo-url: https://github.com/elong0527/demo-tlf-yaml
  repo-actions: [edit, issue, source]
  sharing: [twitter, linkedin]
  reader-mode: true

  chapters:
    - part: "Design"
      chapters:
      - index.qmd
      - docs/inheritance.qmd
      - docs/plan.qmd
    - part: "Adverse Events"
      chapters: 
        - docs/ae_summary.qmd
        - docs/ae_specific.qmd
    - part: "Appendix"
      chapters:
        - docs/count.qmd

format:
  html:
    echo: true
    theme:
      - cosmo
      - custom.scss
    toc: true
    toc-depth: 3
    toc-location: right
    code-fold: false
    code-tools: true
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 250px
      gutter-width: 1.5rem

execute:
  freeze: auto
  cache: true

jupyter: python3